name: food_ordering_app_ui
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

 
  uses-material-design: true

  assets:
    - assets/images/panda.jpg
    - assets/images/image_1.jpeg
    - assets/images/image_2.png
    - assets/images/image_3.jpeg
    - assets/images/image_4.jpeg
    - assets/images/image_5.jpeg

  
